apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-hxlfdtho
  janus-idp.io/tekton: go-hxlfdtho
  backstage.io/kubernetes-id: go-hxlfdtho
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go-hxlfdtho
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
